services:
  langchain-api:
    build:
      context: ./langchain
      dockerfile: Dockerfile
    volumes:
      # - ./langchain:/app
      - ./langchain/perplexity_async:/usr/local/lib/python3.11/site-packages/perplexity_async
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    networks:
      - app-network 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    # tty: true
    # stdin_open: true
    # command: tail -f /dev/null
    command: python main.py api

  wa:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env       
    volumes:
      - ./session1:/app/session1
    depends_on:
      - langchain-api
    networks:
      - app-network 

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: unless-stopped
    command: tunnel --url http://wa:3000
    depends_on:
      - wa
    networks:
      - app-network

networks:
  app-network:
    driver: bridge