services:
  langchain-api:
    build:
      context: ./langchain
      dockerfile: nix-Dockerfile
    volumes:
      - ./langchain:/app
      # - ./langchain/perplexity_async:/usr/local/lib/python3.11/site-packages/perplexity_async
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    tty: true
    stdin_open: true
    command: tail -f /dev/null