version: '3.8'

services:
  langchain-api:
    build:
      context: ./langchain
      dockerfile: Dockerfile
    volumes:
      - ./langchain:/app 
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=8000